import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  primary: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      link: { type: 'doc', id: 'start-here/index' },
      items: [
        'start-here/what-is-an-agentic-business',
      ],
    },
    {
      type: 'category',
      label: 'Principles',
      collapsed: false,
      link: { type: 'doc', id: 'principles/index' },
      items: [
        { type: 'autogenerated', dirName: 'principles' },
      ],
    },
    {
      type: 'category',
      label: 'Mentors',
      collapsed: false,
      link: { type: 'doc', id: 'mentors/index' },
      items: [
        { type: 'autogenerated', dirName: 'mentors' },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: true,
      link: { type: 'doc', id: 'concepts/index' },
      items: [
        { type: 'autogenerated', dirName: 'concepts' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: { type: 'doc', id: 'reference/index' },
      items: [
        {
          type: 'category',
          label: 'Tools',
          link: { type: 'doc', id: 'reference/tools/index' },
          items: [
            { type: 'autogenerated', dirName: 'reference/tools' },
          ],
        },
        'reference/voice-rules',
        'reference/glossary',
      ],
    },
    'changelog',
  ],
};

export default sidebars;
